[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name="maven-ai"
license= "BSD-3-Clause"
description="Metadata Acquisition and Validation ENgine"
readme = "README.md"
requires-python = ">=3.12"
authors=[
	{name = 'Vedant Iyer', 		        email = 'iyer@lanl.gov'},
	{name = 'Christopher W Johnson', 	email = 'cwj@lanl.gov'},
	]
classifiers=["Programming Language :: Python"]
dynamic = ["dependencies","version"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = {attr = "maven._version.__version__"}

[tool.setuptools]
include-package-data = true

[project.scripts]
maven = "maven.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["maven*"]
exclude = ["ursa_workspace"]

[tool.setuptools.package-data]
maven = ["metadata_template/*", ".streamlit/*"]
